machines = {
  "master" => {"memory" => "512", "cpu" => "1", "image" => "bento/ubuntu-24.04", "ip" => "100"},
  "node02" => {"memory" => "512", "cpu" => "1", "image" => "bento/ubuntu-24.04", "ip" => "101"},
  "node03" => {"memory" => "512", "cpu" => "1", "image" => "bento/ubuntu-24.04", "ip" => "102"},
  "node04" => {"memory" => "512", "cpu" => "1", "image" => "bento/ubuntu-24.04", "ip" => "103"}
}

Vagrant.configure("2") do |config|

  machines.each do |name, conf|

    config.vm.define "#{name}" do |machine|
      machine.vm.box = "#{conf["image"]}"
      machine.vm.hostname = "#{name}"
      machine.vm.network "private_network", ip: "10.10.10.#{conf["ip"]}"
      machine.vm.provider "virtualbox" do |vb|
        vb.name = "#{name}"
        vb.memory = conf["memory"]
        vb.cpus = conf["cpu"]
        
      end
      machine.vm.provision "shell", path: "instalar-docker.sh"
      if "#{name}" == "master"
        machine.vm.provision "shell", path: "iac-master.sh"
      else
        machine.vm.provision "shell", path: "iac-worker.sh"
      end
    end
  end
end